# -*- coding: utf-8 -*-
# Generated by Django 1.11.2 on 2017-06-20 00:23
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('nhmfm', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='nhmhosts',
            name='ip',
            field=models.CharField(max_length=13),
        ),
    ]
